[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name          syslog
    Parser        syslog-rfc3164
    Listen        0.0.0.0
    Port          514
    Mode          udp
    Tag           rawlog

[OUTPUT]
    Name          kafka
    Match         rawlog
    Brokers       kafka1:9092,kafka2:9092,kafka3:9092
    Topics        RAWLOG
    Format        json